### PR TITLE
MCPServer: fix workflow lookup in ReplacementDicFromChoice

### PR DESCRIPTION
**Pull request by sevein**
Access to `fallback_link_id` failed because it was using the wrong accessor.

This was introduced in https://github.com/artefactual/archivematica/pull/1251.

Connects to https://github.com/archivematica/Issues/issues/474.

### CODE REVIEW

File: src/MCPServer/lib/linkTaskManagerReplacementDicFromChoice.py [hunk 1]
```diff
@@ -108,7 +108,7 @@ def _get_dashboard_setting_choice(self):
         """
         try:
             link = self.jobChainLink.workflow.get_link(
-                self.jobChainLink.link.config["fallback_link_id"])
+                self.jobChainLink.link["fallback_link_id"])
```
Comment (sevein) [inline src/MCPServer/lib/linkTaskManagerReplacementDicFromChoice.py:111]: `fallback_link_id` is not a member of `config`.

```json
{
    "config": {
        "@manager": "linkTaskManagerDirectories",
        "@model": "StandardTaskConfig",
        "arguments": "--url=\"%url%\"  --email=\"%email%\" --password=\"%password%\" --uuid=\"%SIPUUID%\" --debug=\"%debug%\" --version=\"%version%\" --rsync-command=\"%rsync_command%\" --rsync-target=\"%rsync_target%\"",
        "execute": "upload-qubit_v0.0",
        "filter_file_end": null,
        "filter_file_start": null,
        "filter_subdir": null,
        "stderr_file": null,
        "stdout_file": null
    },
    "description": {
        "en": "Upload DIP",
        "es": "Subir DIP",
        "fr": "Télécharger le DIP",
        "ja": "DIPをアップロード",
        "pt_BR": "Carregar DIP",
        "sv": "Ladda upp DIP"
    },
    "exit_codes": {
        "0": {
            "job_status": "Completed successfully",
            "link_id": "2e31580d-1678-474b-83e5-a53d97d150f6"
        }
    },
    "fallback_job_status": "Failed",
    "fallback_link_id": "2e31580d-1678-474b-83e5-a53d97d150f6",
    "group": {
        "en": "Upload DIP",
        "es": "Subir DIP",
        "fr": "Télécharger le DIP",
        "ja": "DIPをアップロード",
        "pt_BR": "Carregar DIP",
        "sv": "Ladda upp DIP"
    }
}
```

**Review by ablwr — APPROVED** [review]

**Comment by ablwr** [comment]
Small fix for a logical conclusion. :+1:
